/**
 * Press Farm OS — Foraging Calendar Data
 *
 * Seasonal wild-food reference for the SF Bay Area (Marin / East Bay /
 * Peninsula / Santa Cruz Mtns). 85 species across Mushrooms, Wild Greens,
 * Berries, and Fruits. Items marked `isInvasive` show up in the Invasives
 * filter on top of their normal category.
 *
 * Months are 1–12 (Jan = 1). `peak` is the strongest window; `shoulder`
 * extends either side where the item is still findable but past or
 * approaching its window. Microclimates of The Bay routinely shift these
 * windows by 2–6 weeks — treat as rough guidance, not a schedule.
 *
 * Sources cross-referenced from ForageSF, Mycological Society of San
 * Francisco, Bay Nature Magazine, Yerba Buena Chapter CNPS field guides,
 * and "The Bay Area Forager" (Andler & Feinstein, Heyday Books). Always
 * positively identify before consuming, and respect protected areas —
 * foraging is prohibited in most CA state parks and all national parks
 * except for limited personal mushroom quotas in a few.
 */

export type ForageCategory = "mushrooms" | "greens" | "berries" | "fruits";

export type ForageRegion = "marin" | "east-bay" | "peninsula" | "santa-cruz";

export interface ForageItem {
  slug: string;
  name: string;
  scientificName?: string;
  category: ForageCategory;
  /** Bay Area regions where the species is reliably found. */
  regions: ForageRegion[];
  /** Cross-cutting tag — shows up in the Invasives filter regardless of category. */
  isInvasive?: boolean;
  /** Months (1–12) when the item is at peak / ready to harvest. */
  peak: number[];
  /** Months (1–12) where the item is on the way in or fading out. */
  shoulder?: number[];
  habitat: string;
  notes: string;
  /** Optional caution — toxic lookalikes, allergen, or legal restriction. */
  caution?: string;
}

export const CATEGORY_META: Record<
  ForageCategory,
  { label: string; flower: string }
> = {
  mushrooms: { label: "Mushrooms", flower: "buttercup" },
  greens: { label: "Wild Greens", flower: "green-leaf" },
  berries: { label: "Berries", flower: "bachelor-button" },
  fruits: { label: "Fruits", flower: "fennel" },
};

export const REGION_META: Record<ForageRegion, { label: string }> = {
  marin: { label: "Marin & Point Reyes" },
  "east-bay": { label: "East Bay" },
  peninsula: { label: "Peninsula" },
  "santa-cruz": { label: "Santa Cruz Mtns" },
};

export const ALL_REGIONS: ForageRegion[] = ["marin", "east-bay", "peninsula", "santa-cruz"];

export const MONTH_LABELS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

const ALL: ForageRegion[] = ALL_REGIONS;

/**
 * 85 Bay Area forageable species — mushrooms, wild greens, berries, and fruits.
 * Mushroom timing assumes a normal-rain year (slide later in drought, earlier
 * in wet years).
 */
export const FORAGE_ITEMS: ForageItem[] = [
  // ════════════════════════════ MUSHROOMS (25) ════════════════════════════
  {
    slug: "golden-chanterelle",
    name: "Golden Chanterelle",
    scientificName: "Cantharellus californicus",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2],
    shoulder: [10, 3],
    habitat: "Live oak roots — Marin, Sonoma, San Mateo, Santa Cruz coast.",
    notes: "Vase-shaped golden cap with forked false gills (ridges, not blades). Apricot smell when fresh. The Bay's signature mushroom.",
    caution: "Jack-o'-lantern (Omphalotus) has true thin gills and glows green — toxic.",
  },
  {
    slug: "black-trumpet",
    name: "Black Trumpet",
    scientificName: "Craterellus cornucopioides",
    category: "mushrooms",
    regions: ALL,
    peak: [12, 1, 2],
    shoulder: [11, 3],
    habitat: "Tanoak and live oak duff — well-shaded, often mossy.",
    notes: "Hollow charcoal-grey trumpets that hide in plain sight in oak leaf litter. Dries to an intense black-truffle aroma.",
  },
  {
    slug: "hedgehog",
    name: "Hedgehog Mushroom",
    scientificName: "Hydnum repandum / H. umbilicatum",
    category: "mushrooms",
    regions: ALL,
    peak: [12, 1, 2, 3],
    shoulder: [11, 4],
    habitat: "Doug-fir, oak, tanoak — appears alongside chanterelles.",
    notes: "Buff to apricot cap with soft pendulous teeth (not gills, not pores) underneath. Nutty and sweet. No toxic lookalikes — a great beginner ID.",
  },
  {
    slug: "porcini",
    name: "King Bolete / Porcini",
    scientificName: "Boletus edulis",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12],
    shoulder: [1, 9],
    habitat: "Pine, fir, manzanita — fruits ~10 days after a 2-inch rain.",
    notes: "Brown bun cap, spongy white pore surface, no ring, no staining. Thanksgiving is the traditional peak. Don't dry the worm-tunneled ones — slice and check first.",
    caution: "Several look-alike boletes stain blue or have red pores — when in doubt, skip.",
  },
  {
    slug: "yellowfoot",
    name: "Yellowfoot Chanterelle",
    scientificName: "Craterellus tubaeformis",
    category: "mushrooms",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [12, 1, 2],
    shoulder: [11, 3],
    habitat: "Mossy redwood / Doug-fir, often in dense colonies.",
    notes: "Slender hollow stem, yellow base, brown funneled cap. Drier and chewier than golden chants but flushes for weeks.",
  },
  {
    slug: "matsutake",
    name: "Matsutake",
    scientificName: "Tricholoma magnivelare",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [11, 12, 1],
    shoulder: [10, 2],
    habitat: "Tanoak / madrone, coastal CA — Mendocino is famous, also Marin and Santa Cruz.",
    notes: "White-tan cap with a thick ringed stem. Cinnamon-Red-Hots aroma is the ID — if it doesn't smell, it isn't matsi.",
  },
  {
    slug: "candy-cap",
    name: "Candy Cap",
    scientificName: "Lactarius rubidus",
    category: "mushrooms",
    regions: ALL,
    peak: [12, 1, 2],
    shoulder: [11, 3],
    habitat: "Tanoak, live oak — usually scattered, not patchy.",
    notes: "Small rust-orange cap, watery milk when cut, no obvious aroma fresh. Dried, it smells like maple syrup — used in ice cream, panna cotta, biscotti.",
  },
  {
    slug: "morel",
    name: "Morel",
    scientificName: "Morchella spp.",
    category: "mushrooms",
    regions: ["east-bay", "santa-cruz"],
    peak: [4, 5, 6],
    shoulder: [3, 7],
    habitat: "Burn scars and apple/cottonwood floodplains — Sierra foothills mostly, also East Bay burns.",
    notes: "Honeycomb cap completely hollow when sliced. Spring-only and burn-following. False morels (Verpa, Gyromitra) are toxic — true morels are 100% hollow.",
    caution: "Always slice top to bottom — false morels have a cottony interior.",
  },
  {
    slug: "oyster",
    name: "Oyster Mushroom",
    scientificName: "Pleurotus ostreatus / P. pulmonarius",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4],
    shoulder: [10, 5],
    habitat: "Dead or dying alder, oak, cottonwood — usually shelf-stacked on a single trunk.",
    notes: "White-grey shelf with decurrent gills running down a short side stem. Anise scent. The most forgiving cool-season mushroom.",
  },
  {
    slug: "lions-mane",
    name: "Lion's Mane",
    scientificName: "Hericium erinaceus",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12, 1],
    shoulder: [9, 2],
    habitat: "Live oak wounds — often 10–30 feet up the trunk.",
    notes: "White cascading icicle teeth. Cooks down to a seafood-like texture (lobster, crab). No look-alikes in CA.",
  },
  {
    slug: "lobster",
    name: "Lobster Mushroom",
    scientificName: "Hypomyces lactifluorum",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [9, 10, 11, 12],
    habitat: "Fir/spruce, Doug-fir — coastal mountains.",
    notes: "A parasitic mold (Hypomyces) growing on a Russula host. Firm, dense, with shellfish-like flavor. The orange crust is the giveaway.",
  },
  {
    slug: "witches-butter",
    name: "Witch's Butter",
    scientificName: "Tremella mesenterica",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2],
    habitat: "Dead hardwood — bay laurel, oak — after rain.",
    notes: "Jelly-fungus globs of bright yellow on a fallen branch. Flavor-neutral, used in clear broths.",
  },
  {
    slug: "coral-mushroom",
    name: "Coral Mushroom",
    scientificName: "Ramaria spp.",
    category: "mushrooms",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [11, 12, 1, 2],
    habitat: "Mixed conifer / oak duff.",
    notes: "Cauliflower-like cluster of branched tines. Several edible Ramaria species in CA — others are laxative. ID carefully or stick to the named edibles.",
    caution: "Several Ramaria species cause GI upset. Confirm species, not just shape.",
  },
  {
    slug: "shaggy-mane",
    name: "Shaggy Mane",
    scientificName: "Coprinus comatus",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12],
    shoulder: [9, 1],
    habitat: "Disturbed soil — lawns, roadsides, mulch beds — often after rain.",
    notes: "Tall white shaggy cylinder that auto-digests into black ink within 24 hours of picking. Cook same day. One of the few mushrooms you can safely eat without a spore print.",
    caution: "Don't drink alcohol within 48 hours of eating any Coprinus relative.",
  },
  {
    slug: "puffball",
    name: "Puffball",
    scientificName: "Calvatia / Lycoperdon spp.",
    category: "mushrooms",
    regions: ALL,
    peak: [8, 9, 10, 11],
    habitat: "Grasslands, oak savanna, vineyard rows after rain.",
    notes: "White ball, no stem. Slice through — if the interior is pure marshmallow-white (no gill outline, no yellow), it's edible. Tofu-textured, takes any flavor.",
    caution: "Always slice. Button-stage Amanitas (deadly) appear as a white egg before opening — they show a gill outline inside.",
  },
  {
    slug: "turkey-tail",
    name: "Turkey Tail",
    scientificName: "Trametes versicolor",
    category: "mushrooms",
    regions: ALL,
    peak: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    habitat: "Dead hardwood — every fallen oak or bay branch in the Bay.",
    notes: "Concentric zoned bands, leathery. Not food — simmer into a dual-extracted tincture for immune tonic. Underside has tiny pores (not gills, not smooth — that's the false turkey tail).",
  },
  {
    slug: "reishi",
    name: "Reishi (Western)",
    scientificName: "Ganoderma oregonense / G. applanatum",
    category: "mushrooms",
    regions: ALL,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    habitat: "Dead conifer and hardwood — large shelves on stumps.",
    notes: "Lacquered reddish-brown shelf, white margin when growing. Slice fresh and dehydrate; double-decoct for tea or tincture.",
  },
  {
    slug: "cauliflower",
    name: "Cauliflower Mushroom",
    scientificName: "Sparassis crispa / S. radicata",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [10, 11, 12],
    shoulder: [9, 1],
    habitat: "Base of conifers — Doug-fir, pine.",
    notes: "A football-sized cluster of ribbon-like fleshy leaves. Bright cream, no toxic lookalikes. Tear apart and rinse out the duff before cooking.",
  },
  {
    slug: "chicken-of-the-woods",
    name: "Chicken of the Woods",
    scientificName: "Laetiporus gilbertsonii",
    category: "mushrooms",
    regions: ALL,
    peak: [9, 10, 11, 12],
    habitat: "Oak, eucalyptus — bright orange shelves on a live or dead trunk.",
    notes: "Sulfur-yellow and orange shelves with a smooth (no gill) pore underside. Cook well — undercooked or older specimens can cause stomach upset. Sticks to the eucalyptus species are safer cooked thoroughly.",
    caution: "Some people react to Laetiporus on eucalyptus or conifer hosts — start with a small portion.",
  },
  {
    slug: "honey-mushroom",
    name: "Honey Mushroom",
    scientificName: "Armillaria mellea",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12],
    shoulder: [9, 1],
    habitat: "At the base of dying or recently dead hardwood — often a huge cluster.",
    notes: "Honey-brown cap, white gills, ringed stem. Must cook fully — raw or undercooked = GI upset. Discard the tough stems.",
    caution: "Look-alikes include the deadly Galerina — confirm the cobweb-ring on the stem and white spore print.",
  },
  {
    slug: "pigs-ear",
    name: "Pig's Ear",
    scientificName: "Gomphus clavatus",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [10, 11, 12, 1],
    habitat: "Conifer duff, often in fairy-ring clusters.",
    notes: "Vase to ear shape, purplish to ochre, wrinkled spore surface. Mild and good in mixed sautés.",
  },
  {
    slug: "blue-chanterelle",
    name: "Blue Chanterelle",
    scientificName: "Polyozellus multiplex",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [11, 12, 1],
    habitat: "High-elevation conifer — rare in the Bay, more common in Sierra.",
    notes: "Indigo-blue clusters. Sweet, beechnut-like flavor. Treat as a special find.",
  },
  {
    slug: "death-cap",
    name: "Death Cap",
    scientificName: "Amanita phalloides",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2],
    shoulder: [10, 3],
    habitat: "Live oak roots — exactly where chanterelles grow. East Bay parks especially.",
    notes: "Greenish to pale yellow cap, white gills, ringed stem, bulbous cup at the base (volva). The single most dangerous mushroom in California. Learn it cold and never eat any whitish-gilled mushroom from oak duff without ruling it out.",
    caution: "DEADLY — one cap can kill an adult. No reliable home test. Liver and kidney failure 48–72 hours after ingestion.",
  },
  {
    slug: "destroying-angel",
    name: "Western Destroying Angel",
    scientificName: "Amanita ocreata",
    category: "mushrooms",
    regions: ALL,
    peak: [2, 3, 4],
    shoulder: [1, 5],
    habitat: "Live oak — spring counterpart to the death cap.",
    notes: "Pure white throughout, ringed stem, bulbous volva at base. Spring oak season — when you'd be hunting destroying-angel-shaped white mushrooms.",
    caution: "DEADLY — same amatoxin family as Death Cap. Never eat any pure-white gilled mushroom from oak duff.",
  },
  {
    slug: "lobster-of-the-woods",
    name: "Hen of the Woods (Maitake)",
    scientificName: "Grifola frondosa",
    category: "mushrooms",
    regions: ["east-bay"],
    peak: [10, 11],
    habitat: "Base of mature oaks — uncommon in the Bay, but present.",
    notes: "Layered grey-brown clustered fronds at the foot of an oak. Rich, earthy, prized in Japanese cuisine.",
  },

  // ════════════════════════════ WILD GREENS (30) ════════════════════════════
  {
    slug: "miners-lettuce",
    name: "Miner's Lettuce",
    scientificName: "Claytonia perfoliata",
    category: "greens",
    regions: ALL,
    peak: [2, 3, 4, 5],
    shoulder: [1, 6],
    habitat: "Shaded creek banks, oak woodland, north-facing slopes.",
    notes: "Round disk-leaves clasping the stem with a small white flower in the center. Mild, succulent, the gold standard of California wild salad greens.",
  },
  {
    slug: "wild-mustard",
    name: "Wild Mustard",
    scientificName: "Brassica spp.",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [1, 2, 3, 4],
    shoulder: [5, 12],
    habitat: "Disturbed fields, vineyard rows, roadside.",
    notes: "Bright yellow four-petal flowers; leaves and unopened flower buds are pungent like wasabi. Buds are excellent quick-pickled.",
  },
  {
    slug: "stinging-nettle",
    name: "Stinging Nettle",
    scientificName: "Urtica dioica",
    category: "greens",
    regions: ALL,
    peak: [2, 3, 4],
    shoulder: [1, 5],
    habitat: "Damp creek beds, redwood understory, partial shade.",
    notes: "Harvest top 6 inches with gloves before flowering. Loses sting when cooked, dried, or blanched. Tastes between spinach and seaweed.",
    caution: "Wear gloves — formic acid on hairs causes a 24-hour rash.",
  },
  {
    slug: "wood-sorrel",
    name: "Wood Sorrel",
    scientificName: "Oxalis spp.",
    category: "greens",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4, 5],
    shoulder: [6, 10],
    habitat: "Garden edges, redwood duff, lawn shade.",
    notes: "Clover-like trifoliate leaves and yellow or pink flowers. Lemon-bright sour pop. Use as a finish, not a bulk green — oxalic acid.",
    caution: "Avoid daily large servings — high oxalic acid.",
  },
  {
    slug: "wild-fennel",
    name: "Wild Fennel",
    scientificName: "Foeniculum vulgare",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    shoulder: [11, 2],
    habitat: "Roadside, fallow fields, freeway embankments — invasive everywhere in the Bay.",
    notes: "Fronds year-round, pollen in summer, green seed in late summer, brown seed by fall. Pollen is the prize — gold dust over fish or cured meat.",
  },
  {
    slug: "wild-radish",
    name: "Wild Radish",
    scientificName: "Raphanus sativus",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [2, 3, 4, 5, 6],
    habitat: "Same disturbed fields as wild mustard — often growing alongside it.",
    notes: "Lavender or white four-petal flowers (mustard is yellow). Pods are the prize — crisp, peppery, like rat-tail radish. Pickle while still green.",
  },
  {
    slug: "chickweed",
    name: "Chickweed",
    scientificName: "Stellaria media",
    category: "greens",
    regions: ALL,
    peak: [12, 1, 2, 3, 4],
    shoulder: [11, 5],
    habitat: "Garden beds, shaded lawn, irrigated edges.",
    notes: "Sprawling mat with tiny white star flowers and a single line of hair down the stem. Eat raw — corn-silk sweet, lightly grassy.",
  },
  {
    slug: "watercress",
    name: "Watercress",
    scientificName: "Nasturtium officinale",
    category: "greens",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4, 5],
    habitat: "Cold, clean, fast-moving creeks and springs.",
    notes: "Pinnately compound leaves floating on running water. Bright peppery bite.",
    caution: "Only harvest from water you'd drink — giardia and ag runoff risk. Cook if uncertain of source.",
  },
  {
    slug: "purslane",
    name: "Purslane",
    scientificName: "Portulaca oleracea",
    category: "greens",
    regions: ALL,
    peak: [6, 7, 8, 9],
    habitat: "Garden paths, sidewalk cracks, vegetable rows.",
    notes: "Succulent paddle leaves and red stems. Lemony, slightly mucilaginous. Highest plant source of omega-3.",
  },
  {
    slug: "lambs-quarters",
    name: "Lamb's Quarters",
    scientificName: "Chenopodium album",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6, 7, 8],
    habitat: "Same disturbed soil that grows pigweed — vegetable beds, vineyard rows.",
    notes: "Diamond leaves with a powdery silver underside on new growth. Cook like spinach — a goosefoot relative of quinoa.",
  },
  {
    slug: "wild-onion",
    name: "Wild Onion",
    scientificName: "Allium triquetrum / A. unifolium",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6],
    shoulder: [2],
    habitat: "Coastal scrub, oak savanna, road cuts.",
    notes: "If it smells like onion, it's an onion. Three-cornered leek has the most bulb mass. Bulb, leaf, and flower are all usable.",
    caution: "Death camas grows in the same habitat and is fatal — only harvest plants that smell of onion when crushed.",
  },
  {
    slug: "yerba-buena",
    name: "Yerba Buena",
    scientificName: "Clinopodium douglasii",
    category: "greens",
    regions: ALL,
    peak: [5, 6, 7, 8, 9],
    shoulder: [4, 10],
    habitat: "Redwood / Doug-fir understory, well-drained shade.",
    notes: "The 'good herb' that named San Francisco. Trailing mint vine — soft, sweet, restorative tea.",
  },
  {
    slug: "cleavers",
    name: "Cleavers",
    scientificName: "Galium aparine",
    category: "greens",
    regions: ALL,
    peak: [2, 3, 4, 5],
    habitat: "Hedgerows, fence lines, partial shade.",
    notes: "Velcro-sticky whorled leaves. Best as a cold infusion (steep in cool water overnight) — bright cucumber finish.",
  },
  {
    slug: "mallow",
    name: "Common Mallow",
    scientificName: "Malva neglecta",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    habitat: "Sidewalk strips, neglected lots, garden edges.",
    notes: "Round scalloped leaves and small lavender flowers. Tender leaves cook to a silky, slightly mucilaginous green — thickens soups.",
  },
  {
    slug: "sea-beans",
    name: "Sea Beans / Pickleweed",
    scientificName: "Salicornia pacifica",
    category: "greens",
    regions: ["marin", "east-bay", "peninsula"],
    peak: [5, 6, 7, 8, 9],
    habitat: "Salt marsh edges — San Pablo Bay, Drakes Estero, Tomales.",
    notes: "Jointed succulent stems. Crisp and pre-salted. Pinch the tender tips only.",
    caution: "Marsh harvest is regulated in many CA preserves — check refuge rules.",
  },
  {
    slug: "sow-thistle",
    name: "Sow Thistle",
    scientificName: "Sonchus oleraceus",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6, 7],
    shoulder: [2, 8, 9],
    habitat: "Disturbed soil, garden edges, sidewalk strips.",
    notes: "Soft-spined dandelion relative with bigger, milder leaves. Cook out the bitterness like cultivated chicory.",
  },
  {
    slug: "plantain",
    name: "Broadleaf Plantain",
    scientificName: "Plantago major / P. lanceolata",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    habitat: "Lawns, trail edges, compacted soil.",
    notes: "Parallel-veined leaves in a flat rosette. Young leaves cook tender; older ones are fibrous. Crushed leaves draw bee stings and itches.",
  },
  {
    slug: "wild-asparagus",
    name: "Wild Asparagus",
    scientificName: "Asparagus officinalis",
    category: "greens",
    regions: ["east-bay", "marin"],
    peak: [4, 5],
    shoulder: [3, 6],
    habitat: "Old railroad cuts, ag escapees along ditches.",
    notes: "Look for last year's tall ferny stalks in early spring — that's where this year's spears will push up. Snap, don't cut.",
  },
  {
    slug: "curly-dock",
    name: "Curly Dock",
    scientificName: "Rumex crispus",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6],
    shoulder: [2, 7],
    habitat: "Field edges, pasture, damp lots.",
    notes: "Long ruffle-edged leaves with a strong sour-lemon punch. Cook to soften. Seeds in fall grind into a buckwheat-style flour.",
    caution: "Oxalic acid — moderate intake only.",
  },
  {
    slug: "cattail",
    name: "Cattail",
    scientificName: "Typha latifolia",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6],
    shoulder: [7, 3],
    habitat: "Freshwater marsh, pond edges, slow streams.",
    notes: "Spring shoots peel like leeks. Green corn-dog heads are edible boiled before they go to fluff. Pollen in early summer is a golden flour.",
    caution: "Marsh harvest may be restricted in preserves and refuges — check land-use rules.",
  },
  {
    slug: "dandelion",
    name: "Dandelion",
    scientificName: "Taraxacum officinale",
    category: "greens",
    regions: ALL,
    peak: [2, 3, 4, 5],
    shoulder: [1, 6, 11, 12],
    habitat: "Lawns, roadsides, vineyard floor — universal.",
    notes: "Toothed-leaf rosette, single yellow flower per hollow stem (compound flowers = false dandelion). Pre-flower leaves are mildest; roast roots as coffee.",
  },
  {
    slug: "new-zealand-spinach",
    name: "New Zealand Spinach",
    scientificName: "Tetragonia tetragonoides",
    category: "greens",
    regions: ["marin", "peninsula", "santa-cruz"],
    isInvasive: true,
    peak: [5, 6, 7, 8, 9, 10],
    habitat: "Coastal bluffs, beach edges — naturalized along the whole CA coast.",
    notes: "Diamond-shaped fleshy leaves. Cooks down identically to spinach. Blanch briefly to drop oxalates.",
    caution: "High oxalic acid — always blanch before eating.",
  },
  {
    slug: "shepherds-purse",
    name: "Shepherd's Purse",
    scientificName: "Capsella bursa-pastoris",
    category: "greens",
    regions: ALL,
    peak: [1, 2, 3, 4, 11, 12],
    shoulder: [5, 10],
    habitat: "Garden beds, gravel paths, winter rows.",
    notes: "Heart-shaped seed pods are the giveaway. Leaves taste like peppery cabbage; pods are a tiny mustard pop on top of fish or eggs.",
  },
  {
    slug: "bittercress",
    name: "Hairy Bittercress",
    scientificName: "Cardamine hirsuta",
    category: "greens",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4],
    habitat: "Winter rains anywhere with bare soil — nurseries, garden edges.",
    notes: "Tiny rosette of round leaflets with explosive seed pods. Bright peppery, exactly like watercress, with no waterborne pathogen risk.",
  },
  {
    slug: "mugwort",
    name: "Mugwort",
    scientificName: "Artemisia douglasiana",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6, 7],
    habitat: "Creek bottoms, oak woodland edges.",
    notes: "Silver-backed lobed leaves with a strong sage-bay scent. Bitter — use as a smoking herb, dream pillow, or moxa, not a salad green.",
    caution: "Avoid during pregnancy.",
  },
  {
    slug: "pineapple-weed",
    name: "Pineapple Weed",
    scientificName: "Matricaria discoidea",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6, 7, 8],
    habitat: "Compacted gravel — driveways, trail centers, parking lots.",
    notes: "Looks like rayless chamomile; crushed flowers smell like pineapple. Steeped fresh or dried into the gentlest of teas.",
  },
  {
    slug: "sourgrass",
    name: "Sourgrass / Bermuda Buttercup",
    scientificName: "Oxalis pes-caprae",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [11, 12, 1, 2, 3, 4],
    habitat: "Carpets every shaded yard, vineyard floor, and park edge through winter.",
    notes: "Yellow five-petal flower, clover leaf. Hollow stems suck like sour straws. A pungent finish to fish, not a bulk salad.",
    caution: "High oxalic acid — small quantities only.",
  },
  {
    slug: "wild-garlic",
    name: "Crow Garlic",
    scientificName: "Allium vineale",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6],
    habitat: "Pasture edges, vineyard rows.",
    notes: "Thin tubular leaves that smell unmistakably of garlic. Bulblets at the top of the flower stem are a free seed crop.",
    caution: "Same lookalike warning as wild onion — death camas. Crush and smell first.",
  },
  {
    slug: "yerba-santa",
    name: "Yerba Santa",
    scientificName: "Eriodictyon californicum",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6, 7, 8],
    habitat: "Dry chaparral slopes — common after fire.",
    notes: "Sticky-resinous lance leaves and lavender trumpet flowers. Bitter-sweet steeped tea, traditional respiratory remedy.",
  },
  {
    slug: "salsify",
    name: "Salsify",
    scientificName: "Tragopogon porrifolius",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6],
    habitat: "Disturbed open ground, road cuts.",
    notes: "Grass-like leaves with a big purple dandelion-style seed head. Root tastes faintly of oyster when roasted; young flower stems are a vegetable like asparagus.",
  },
  {
    slug: "elderflower",
    name: "Elderflower",
    scientificName: "Sambucus nigra ssp. caerulea",
    category: "greens",
    regions: ALL,
    peak: [5, 6],
    shoulder: [4, 7],
    habitat: "Stream banks, road cuts, oak woodland edges.",
    notes: "Cream-white umbels with a musky-floral aroma. Cordial, fritters, vinegar. Snip only a fraction of each tree's blooms — those become the August berries.",
  },
  {
    slug: "wild-fennel-pollen",
    name: "Wild Fennel Pollen",
    scientificName: "Foeniculum vulgare",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [6, 7, 8],
    habitat: "Same fennel stalks — flower umbels in mid-summer.",
    notes: "Tap full umbels into a paper bag, sift out the chaff. Pure pollen sells for $40/oz and tastes like fennel × anise × honey.",
  },
  {
    slug: "wild-rose-petals",
    name: "Wild Rose Petals",
    scientificName: "Rosa californica",
    category: "greens",
    regions: ALL,
    peak: [5, 6, 7],
    shoulder: [4, 8],
    habitat: "Coastal scrub, riparian — the California wild rose is everywhere.",
    notes: "Pink five-petal flowers, intensely fragrant on a warm afternoon. Petal sugars, vinegar, syrup; pluck the white heel off each petal to drop the bitterness.",
  },
  {
    slug: "wild-mustard-flowers",
    name: "Wild Mustard Flowers",
    scientificName: "Brassica spp.",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [2, 3, 4, 5],
    habitat: "Same plant as wild mustard greens — separate harvest.",
    notes: "Bright yellow four-petal sprays. Sweet-spicy, beautiful as a garnish or quick-pickled.",
  },
  {
    slug: "bay-laurel",
    name: "California Bay (Leaves)",
    scientificName: "Umbellularia californica",
    category: "greens",
    regions: ALL,
    peak: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    habitat: "Coastal mixed forest, creek bottoms.",
    notes: "Far more aromatic than Mediterranean bay — half a leaf per stew. Dry on the counter for a week before storing.",
    caution: "Strong oils. Never use for tea or baby food.",
  },
  {
    slug: "nori",
    name: "Wild Nori",
    scientificName: "Porphyra perforata",
    category: "greens",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [5, 6, 7, 8],
    shoulder: [4, 9],
    habitat: "Mid-intertidal rocks — Sonoma, Marin, and San Mateo coast.",
    notes: "Dark purple sheets that dry to glossy black. Harvest with scissors above the holdfast so it regrows.",
    caution: "Requires a CA recreational fishing license. Daily limit: 10 lbs wet weight.",
  },
  {
    slug: "wakame",
    name: "Wakame",
    scientificName: "Alaria marginata",
    category: "greens",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [4, 5, 6, 7],
    habitat: "Low-tide rocky reefs.",
    notes: "The lasagna-noodle ribbed brown blade. Blanches to bright green; classic miso-soup texture.",
    caution: "Fishing license required.",
  },
  {
    slug: "kombu",
    name: "Kombu / Giant Kelp",
    scientificName: "Macrocystis pyrifera",
    category: "greens",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [4, 5, 6, 7, 8, 9],
    habitat: "Subtidal forests — float in beach-wrack at low tide.",
    notes: "Beach-cast fresh blades dry to dashi-grade stock material in two sunny days. Take only what's intact and salty-fresh.",
  },
  {
    slug: "sea-lettuce",
    name: "Sea Lettuce",
    scientificName: "Ulva spp.",
    category: "greens",
    regions: ["marin", "east-bay", "peninsula", "santa-cruz"],
    peak: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    habitat: "Tide pools, brackish bay edges.",
    notes: "Bright translucent green sheet. Mild grassy flavor; best crisped in oil. Year-round if water is cold and clean.",
    caution: "Avoid harvesting near urban outfalls or marinas.",
  },
  {
    slug: "bull-kelp",
    name: "Bull Kelp",
    scientificName: "Nereocystis luetkeana",
    category: "greens",
    regions: ["marin", "santa-cruz"],
    peak: [5, 6, 7, 8, 9],
    habitat: "Subtidal kelp forests — Mendocino especially.",
    notes: "The long-stipe bullwhip kelp. Stipe pickles like rings; blade dries for snacks. Populations are stressed by urchin grazing — harvest beach-cast first.",
    caution: "Critical habitat — recreational limit and license required; consider skipping if local forests are crashing.",
  },

  // ════════════════════════════ BERRIES (15) ════════════════════════════
  {
    slug: "wild-blackberry",
    name: "Himalayan Blackberry",
    scientificName: "Rubus armeniacus",
    category: "berries",
    regions: ALL,
    isInvasive: true,
    peak: [7, 8, 9],
    shoulder: [6, 10],
    habitat: "Every creek bank, fence line, and disturbed edge in the Bay.",
    notes: "Invasive, abundant, and excellent. Pick when berries pull off the receptacle with no tug. Highest sugar after a hot week.",
  },
  {
    slug: "california-blackberry",
    name: "California Blackberry",
    scientificName: "Rubus ursinus",
    category: "berries",
    regions: ALL,
    peak: [6, 7, 8],
    habitat: "Native cousin of the Himalayan — smaller berries, thinner canes, found in deeper woods.",
    notes: "Less prolific than Himalayan but more nuanced — concentrated berry flavor and a slight winey edge. The parent of the cultivated boysenberry.",
  },
  {
    slug: "thimbleberry",
    name: "Thimbleberry",
    scientificName: "Rubus parviflorus",
    category: "berries",
    regions: ["marin", "santa-cruz"],
    peak: [6, 7, 8],
    habitat: "Redwood understory, coastal shade.",
    notes: "Maple-shaped fuzzy leaves, no thorns. Soft, fragile red caps that fall apart in the hand — eat trail-side or carry on a flat board.",
  },
  {
    slug: "wild-strawberry",
    name: "Beach Strawberry",
    scientificName: "Fragaria chiloensis",
    category: "berries",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [5, 6, 7],
    habitat: "Coastal bluffs and dunes.",
    notes: "Tiny berries with concentrated flavor — the parent of the cultivated strawberry. Harvest small or you'll never get a quart.",
  },
  {
    slug: "salmonberry",
    name: "Salmonberry",
    scientificName: "Rubus spectabilis",
    category: "berries",
    regions: ["marin"],
    peak: [5, 6, 7],
    habitat: "Wet coastal forest, North Bay creeks.",
    notes: "Golden to salmon-orange raspberry shape. Earliest cane berry of the year. Better in pie than eaten plain.",
  },
  {
    slug: "huckleberry",
    name: "Evergreen Huckleberry",
    scientificName: "Vaccinium ovatum",
    category: "berries",
    regions: ["marin", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Acidic redwood / Doug-fir soil.",
    notes: "Small dark berries on glossy evergreen leaves. Sweet-tart, smaller than cultivated blueberry, with a longer shelf life.",
  },
  {
    slug: "blue-elderberry",
    name: "Blue Elderberry",
    scientificName: "Sambucus nigra ssp. caerulea",
    category: "berries",
    regions: ALL,
    peak: [8, 9],
    shoulder: [7],
    habitat: "Stream banks, oak woodland edges.",
    notes: "Powder-blue clusters on umbrella stems. Must cook — raw berries are unpleasantly cyanogenic. Stems and leaves are always toxic.",
    caution: "Red elderberry (S. racemosa) is generally not eaten — only harvest the blue/black species, cooked.",
  },
  {
    slug: "manzanita",
    name: "Manzanita Berry",
    scientificName: "Arctostaphylos spp.",
    category: "berries",
    regions: ALL,
    peak: [8, 9],
    habitat: "Chaparral, granite slopes.",
    notes: "'Little apples' — dry, mealy, intensely apple-flavored. Best cold-water steeped into a cider or pressed for syrup. Don't try to eat raw.",
  },
  {
    slug: "wild-grape",
    name: "California Wild Grape",
    scientificName: "Vitis californica",
    category: "berries",
    regions: ALL,
    peak: [8, 9, 10],
    habitat: "River corridors throughout the Bay.",
    notes: "Small intensely tart blue grapes with big seeds. Leaves for dolmas, fruit for verjus and jelly.",
  },
  {
    slug: "prickly-pear",
    name: "Prickly Pear (Tuna)",
    scientificName: "Opuntia ficus-indica",
    category: "berries",
    regions: ALL,
    isInvasive: true,
    peak: [8, 9, 10],
    habitat: "Old homesteads, naturalized on dry slopes.",
    notes: "Magenta fruit. Singe glochids off over a flame or scrub under running water before peeling. Watermelon-bubblegum sweetness.",
    caution: "Glochids — tiny barbed hairs — embed in skin and persist. Always use tongs and gloves.",
  },
  {
    slug: "rose-hips",
    name: "Rose Hips",
    scientificName: "Rosa californica",
    category: "berries",
    regions: ALL,
    peak: [9, 10, 11],
    habitat: "Coastal scrub, riparian — California wild rose is everywhere.",
    notes: "Best after the first frost. Split, scrape seeds (irritating fuzz), and use the flesh for syrup, jelly, or vitamin-C tea.",
  },
  {
    slug: "salal",
    name: "Salal Berry",
    scientificName: "Gaultheria shallon",
    category: "berries",
    regions: ["marin", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Coastal Doug-fir / redwood understory.",
    notes: "Dark blue-black berries on leathery oval leaves. Mealy texture, mild blueberry-grape flavor — better cooked into jam than eaten raw.",
  },
  {
    slug: "toyon",
    name: "Toyon (Christmas Berry)",
    scientificName: "Heteromeles arbutifolia",
    category: "berries",
    regions: ALL,
    peak: [11, 12, 1],
    habitat: "Chaparral and oak woodland, all regions.",
    notes: "Bright red clusters at Christmas-time. Native peoples roasted or boiled them — never eat raw (cyanogenic, like blue elderberry). Cook into jelly or roasted nibble.",
    caution: "Raw berries contain cyanogenic compounds — always cook.",
  },
  {
    slug: "ribes-currant",
    name: "California Wild Currant",
    scientificName: "Ribes californicum",
    category: "berries",
    regions: ALL,
    peak: [5, 6, 7],
    habitat: "Oak understory, shaded riparian.",
    notes: "Pink-red fuchsia-shaped flowers in winter give way to small tart red berries in early summer. Best as preserves; berry-to-pith ratio is low.",
  },
  {
    slug: "wild-gooseberry",
    name: "Native Gooseberry",
    scientificName: "Ribes spp.",
    category: "berries",
    regions: ALL,
    peak: [5, 6, 7],
    habitat: "Mixed evergreen forest, riparian shade.",
    notes: "Spiny green berry. Several CA species — most ripen to dark purple-red. Cook into pies, sorbet, or savory pan sauces.",
  },

  // ════════════════════════════ FRUITS (15) ════════════════════════════
  {
    slug: "wild-plum",
    name: "Cherry-Plum",
    scientificName: "Prunus cerasifera",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [6, 7, 8],
    habitat: "Roadside escapees from old orchards — common in East Bay and Marin.",
    notes: "Cherry-sized red or yellow plums on what looks like an ornamental tree. Wide flavor range tree-to-tree — taste before you fill a bag.",
  },
  {
    slug: "sierra-plum",
    name: "Sierra Plum",
    scientificName: "Prunus subcordata",
    category: "fruits",
    regions: ["east-bay", "santa-cruz"],
    peak: [7, 8, 9],
    habitat: "Foothill oak woodland — native CA plum.",
    notes: "Yellow-orange to red plum, sharper and more aromatic than store plums. Excellent for fruit leather and umeshu-style infusions.",
  },
  {
    slug: "wild-apple",
    name: "Feral Apple / Crabapple",
    scientificName: "Malus spp.",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [8, 9, 10],
    habitat: "Abandoned homesteads, fence lines, road cuts.",
    notes: "Old apple plantings revert and pop up everywhere. Crabapples are tart but make peerless jelly thanks to high pectin.",
  },
  {
    slug: "loquat",
    name: "Loquat",
    scientificName: "Eriobotrya japonica",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [4, 5],
    shoulder: [3, 6],
    habitat: "Naturalized in older Bay Area neighborhoods — front yards, alleys, hill paths.",
    notes: "Yellow-orange thumb-sized fruit with a few large seeds. Tropical-bright, like mango × apricot. Pick when soft to the touch — they don't ripen off the tree.",
    caution: "Seeds are cyanogenic — never crush or eat them.",
  },
  {
    slug: "feral-olive",
    name: "Feral Olive",
    scientificName: "Olea europaea",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [10, 11, 12],
    habitat: "Naturalized along old Mission corridors and freeway plantings.",
    notes: "Inedible raw — bitterness needs a brine or lye cure (~6 weeks) before eating. Worth doing for an old-tree harvest.",
    caution: "Raw olives are essentially inedible. Cure properly before eating.",
  },
  {
    slug: "madrone",
    name: "Madrone Berry",
    scientificName: "Arbutus menziesii",
    category: "fruits",
    regions: ALL,
    peak: [9, 10, 11],
    habitat: "Mixed evergreen and oak forest — all regions.",
    notes: "Pebbly red-orange berries from the iconic peeling-bark tree. Mealy and lightly sweet — historically a flour ingredient and a cider base.",
  },
  {
    slug: "persimmon",
    name: "Feral Persimmon",
    scientificName: "Diospyros kaki",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [10, 11, 12],
    habitat: "Naturalized in older yards and parkland.",
    notes: "Hachiya types must be jelly-soft (astringent until then). Fuyu types are crunch-ripe like an apple. Both freeze and dehydrate well.",
  },
  {
    slug: "wild-pear",
    name: "Feral Pear",
    scientificName: "Pyrus spp.",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [8, 9, 10],
    habitat: "Old homesteads, abandoned orchards.",
    notes: "Often tougher and more aromatic than supermarket pears. Pick firm, ripen on the counter, or press straight into perry (pear cider).",
  },
  {
    slug: "pyracantha",
    name: "Pyracantha (Firethorn)",
    scientificName: "Pyracantha spp.",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [10, 11, 12, 1],
    habitat: "Hedges, freeway plantings, old yards.",
    notes: "Bright red-orange clusters all winter. Cook into jelly or syrup — raw they're insipid and the seeds are cyanogenic. Watch the thorns.",
    caution: "Seeds are cyanogenic. Cook and strain.",
  },
  {
    slug: "bay-nuts",
    name: "California Bay Nuts",
    scientificName: "Umbellularia californica",
    category: "fruits",
    regions: ALL,
    peak: [10, 11, 12],
    habitat: "Beneath bay laurel — drop in late fall.",
    notes: "Olive-shaped green-purple fruit; the seed inside is the prize. Roast at 400°F for 15 minutes, peel — tastes like dark chocolate × coffee × bay.",
    caution: "Always roast — raw nuts have psychoactive umbellulone.",
  },
  {
    slug: "black-walnut",
    name: "Black Walnut",
    scientificName: "Juglans hindsii",
    category: "fruits",
    regions: ALL,
    peak: [9, 10, 11],
    habitat: "Old farms, East Bay and North Bay riparian — often planted by homesteaders.",
    notes: "Husk first while still green for pickled walnuts, or wait for the husk to blacken for the nut. Stains everything indelibly — work outside in gloves.",
    caution: "Juglone in husks is irritating and can kill nearby garden plants.",
  },
  {
    slug: "english-walnut",
    name: "Feral English Walnut",
    scientificName: "Juglans regia",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [9, 10],
    habitat: "Old orchards, residential yards gone wild.",
    notes: "Thinner-shelled and milder than black walnut. Knock or shake mature trees — husks come off cleanly when fully ripe.",
  },
  {
    slug: "acorn",
    name: "Acorn (Tan Oak / Live Oak)",
    scientificName: "Notholithocarpus / Quercus spp.",
    category: "fruits",
    regions: ALL,
    peak: [10, 11],
    shoulder: [9, 12],
    habitat: "Beneath any local oak — tanoak preferred for size.",
    notes: "Crack, leach in cold running water 1–2 weeks (or 6–8 boil changes) until no astringency. Mill into flour for cakes, pancakes, mush. Indigenous staple here.",
    caution: "Unleached acorns are inedible from tannin content.",
  },
  {
    slug: "california-hazelnut",
    name: "California Hazelnut",
    scientificName: "Corylus cornuta var. californica",
    category: "fruits",
    regions: ["marin", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Cool shaded canyons, redwood / Doug-fir understory.",
    notes: "Small wild filbert with a long bristly husk. Race the squirrels — they go fast. Roast lightly to peel the brown skin.",
  },
  {
    slug: "pine-nut",
    name: "Gray Pine Nut",
    scientificName: "Pinus sabiniana",
    category: "fruits",
    regions: ["east-bay", "marin", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Foothill gray (digger) pine.",
    notes: "Massive cones (heavy enough to dent a car). Roast cones to spring them open; large rich seeds inside.",
    caution: "Pine cones can fall from 60 feet — don't stand under bearing trees in wind.",
  },
];

/**
 * Item count per category — used by the filter chips.
 */
export function countByCategory(): Record<ForageCategory, number> {
  return FORAGE_ITEMS.reduce(
    (acc, item) => {
      acc[item.category]++;
      return acc;
    },
    { mushrooms: 0, greens: 0, berries: 0, fruits: 0 } as Record<ForageCategory, number>,
  );
}

export function countInvasive(): number {
  return FORAGE_ITEMS.filter((i) => i.isInvasive).length;
}

/**
 * Items in peak in a given month — used by the spotlight and "X species can be
 * found in {month}" stat.
 */
export function itemsInPeak(month: number): ForageItem[] {
  return FORAGE_ITEMS.filter((i) => i.peak.includes(month));
}

/**
 * Items where the given month is either peak or shoulder — used for the
 * Month View species count (matches Bay Forager's tally).
 */
export function itemsAvailable(month: number): ForageItem[] {
  return FORAGE_ITEMS.filter(
    (i) => i.peak.includes(month) || i.shoulder?.includes(month),
  );
}
