/**
 * Press Farm OS — Foraging Calendar Data
 *
 * Bay Area seasonal foraging reference, mirroring thebayforager.com's
 * 85-species catalog. Categories, regions, and species names are matched
 * to their site. Months are 1–12 (Jan = 1). `peak` is the strongest
 * window; `shoulder` extends either side where the item is still findable.
 *
 * Microclimates of The Bay routinely shift these windows by 2–6 weeks —
 * treat peak and shoulder ratings as rough guidance, not a schedule.
 *
 * Sources: thebayforager.com, ForageSF, Mycological Society of San
 * Francisco, Bay Nature, Yerba Buena Chapter CNPS, and "The Bay Area
 * Forager" (Andler & Feinstein, Heyday Books). Always positively identify
 * before consuming, and respect protected areas — foraging is prohibited
 * in most CA state parks and all national parks except for limited
 * personal mushroom quotas in a few.
 */

export type ForageCategory = "mushrooms" | "greens" | "berries" | "fruits";

export type ForageRegion = "marin" | "east-bay" | "peninsula" | "santa-cruz";

export interface ForageItem {
  slug: string;
  name: string;
  scientificName?: string;
  category: ForageCategory;
  /** Bay Area regions where the species is reliably found. */
  regions: ForageRegion[];
  /** Cross-cutting tag — shows up in the Invasives filter regardless of category. */
  isInvasive?: boolean;
  /** Months (1–12) when the item is at peak / ready to harvest. */
  peak: number[];
  /** Months (1–12) where the item is on the way in or fading out. */
  shoulder?: number[];
  habitat: string;
  notes: string;
  /** Optional caution — toxic lookalikes, allergen, or legal restriction. */
  caution?: string;
  /**
   * Override for the Wikipedia page used to source the identification photo.
   * Defaults to scientificName with underscores (with "spp." stripped). Only
   * set when the auto-derived title doesn't match a real WP page.
   */
  wikiTitle?: string;
}

/**
 * Derive the Wikipedia page title for a foraging item. Used by the
 * client-side image fetcher to pull a thumbnail from the Wikipedia REST
 * API for identification.
 */
export function wikiTitleFor(item: ForageItem): string {
  if (item.wikiTitle) return item.wikiTitle;
  if (item.scientificName) {
    return item.scientificName
      .replace(/\s+spp\.$/i, "")
      .trim()
      .replace(/\s+/g, "_");
  }
  return item.name.replace(/\s+/g, "_");
}

export const CATEGORY_META: Record<
  ForageCategory,
  { label: string; flower: string }
> = {
  mushrooms: { label: "Mushrooms", flower: "buttercup" },
  greens: { label: "Wild Greens", flower: "green-leaf" },
  berries: { label: "Berries", flower: "bachelor-button" },
  fruits: { label: "Fruits", flower: "fennel" },
};

export const REGION_META: Record<ForageRegion, { label: string }> = {
  marin: { label: "Marin & Point Reyes" },
  "east-bay": { label: "East Bay" },
  peninsula: { label: "Peninsula" },
  "santa-cruz": { label: "Santa Cruz Mtns" },
};

export const ALL_REGIONS: ForageRegion[] = ["marin", "east-bay", "peninsula", "santa-cruz"];

export const MONTH_LABELS = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

const ALL: ForageRegion[] = ALL_REGIONS;

/**
 * 85 Bay Area foragable species. Species names, scientific names, and
 * category assignments mirror thebayforager.com. Region tags reflect
 * where each species is reliably found across the four BF regions.
 */
export const FORAGE_ITEMS: ForageItem[] = [
  // ════════════════════════════ MUSHROOMS (25) ════════════════════════════
  {
    slug: "golden-chanterelle",
    name: "Golden Chanterelle",
    scientificName: "Cantharellus californicus",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2, 3],
    shoulder: [10, 4],
    habitat: "Live oak roots — Marin, East Bay, Peninsula, Santa Cruz.",
    notes: "Vase-shaped golden cap with forked false gills (ridges, not blades). Apricot smell when fresh. The Bay's signature mushroom.",
    caution: "Jack-o'-lantern (Omphalotus) has true thin gills and glows green — toxic.",
  },
  {
    slug: "pacific-golden-chanterelle",
    name: "Pacific Golden Chanterelle",
    scientificName: "Cantharellus formosus",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [10, 11, 12, 1, 2],
    shoulder: [9, 3],
    habitat: "Doug-fir and tanoak forests, coastal — distinct from C. californicus by smaller size and conifer host.",
    notes: "Smaller and more delicate than the Bay's namesake chanterelle. Same forked false gills, same apricot perfume. Often found alongside hedgehogs.",
  },
  {
    slug: "yellowfoot",
    name: "Yellowfoot Chanterelle",
    scientificName: "Craterellus tubaeformis",
    category: "mushrooms",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [12, 1, 2],
    shoulder: [11, 3],
    habitat: "Mossy redwood / Doug-fir, often in dense colonies.",
    notes: "Slender hollow stem, yellow base, brown funneled cap. Drier and chewier than golden chants but flushes for weeks.",
  },
  {
    slug: "oyster",
    name: "Oyster Mushroom",
    scientificName: "Pleurotus ostreatus",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4],
    shoulder: [10, 5],
    habitat: "Dead or dying alder, oak, cottonwood — usually shelf-stacked on a single trunk.",
    notes: "White-grey shelf with decurrent gills running down a short side stem. Anise scent. The most forgiving cool-season mushroom.",
  },
  {
    slug: "hedgehog",
    name: "Hedgehog Mushroom",
    scientificName: "Hydnum repandum",
    category: "mushrooms",
    regions: ALL,
    peak: [12, 1, 2, 3],
    shoulder: [11, 4],
    habitat: "Doug-fir, oak, tanoak — appears alongside chanterelles.",
    notes: "Buff to apricot cap with soft pendulous teeth (not gills, not pores) underneath. Nutty and sweet. No toxic lookalikes — a great beginner ID.",
  },
  {
    slug: "candy-cap",
    name: "Candy Cap",
    scientificName: "Lactarius rubidus",
    category: "mushrooms",
    regions: ALL,
    peak: [12, 1, 2, 3],
    shoulder: [11, 4],
    habitat: "Tanoak, live oak — usually scattered, not patchy.",
    notes: "Small rust-orange cap, watery milk when cut, no obvious aroma fresh. Dried, it smells like maple syrup — used in ice cream, panna cotta, biscotti.",
  },
  {
    slug: "black-trumpet",
    name: "Black Trumpet",
    scientificName: "Craterellus cornucopioides",
    category: "mushrooms",
    regions: ALL,
    peak: [12, 1, 2],
    shoulder: [11, 3],
    habitat: "Tanoak and live oak duff — well-shaded, often mossy.",
    notes: "Hollow charcoal-grey trumpets that hide in plain sight in oak leaf litter. Dries to an intense black-truffle aroma.",
  },
  {
    slug: "porcini",
    name: "King Bolete / Porcini",
    scientificName: "Boletus edulis",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12],
    shoulder: [1, 9],
    habitat: "Pine, fir, manzanita — fruits ~10 days after a 2-inch rain.",
    notes: "Brown bun cap, spongy white pore surface, no ring, no staining. Thanksgiving is the traditional peak. Slice and check for worm tunnels before drying.",
    caution: "Look-alike boletes stain blue or have red pores — when in doubt, skip.",
  },
  {
    slug: "matsutake",
    name: "Matsutake",
    scientificName: "Tricholoma murrillianum",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [10, 11, 12, 1],
    shoulder: [9, 2],
    habitat: "Tanoak / madrone, coastal CA — Marin headlands and Santa Cruz uplands.",
    notes: "White-tan cap with a thick ringed stem. Cinnamon-Red-Hots aroma is the ID — if it doesn't smell, it isn't matsi.",
  },
  {
    slug: "lions-mane",
    name: "Lion's Mane",
    scientificName: "Hericium erinaceus",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12, 1],
    shoulder: [9, 2],
    habitat: "Live oak wounds — often 10–30 feet up the trunk.",
    notes: "White cascading icicle teeth. Cooks down to a seafood-like texture (lobster, crab). No look-alikes in CA.",
  },
  {
    slug: "chicken-of-the-woods",
    name: "Chicken of the Woods",
    scientificName: "Laetiporus gilbertsonii",
    wikiTitle: "Laetiporus",
    category: "mushrooms",
    regions: ALL,
    peak: [9, 10, 11, 12],
    habitat: "Oak, eucalyptus — bright orange shelves on a live or dead trunk.",
    notes: "Sulfur-yellow and orange shelves with a smooth pore underside (no gills). Cook well — undercooked or older specimens can cause stomach upset.",
    caution: "Some people react to Laetiporus on eucalyptus or conifer hosts — start with a small portion.",
  },
  {
    slug: "morel",
    name: "Morel",
    scientificName: "Morchella spp.",
    category: "mushrooms",
    regions: ["east-bay", "santa-cruz"],
    peak: [4, 5, 6],
    shoulder: [3, 7],
    habitat: "Burn scars and apple/cottonwood floodplains — Sierra foothills primarily, also East Bay burns.",
    notes: "Honeycomb cap completely hollow when sliced. Spring-only and burn-following. False morels (Verpa, Gyromitra) are toxic — true morels are 100% hollow.",
    caution: "Always slice top to bottom — false morels have a cottony interior.",
  },
  {
    slug: "turkey-tail",
    name: "Turkey Tail",
    scientificName: "Trametes versicolor",
    category: "mushrooms",
    regions: ALL,
    peak: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    habitat: "Dead hardwood — every fallen oak or bay branch in the Bay.",
    notes: "Concentric zoned bands, leathery. Not food — simmer into a dual-extracted tincture for immune tonic. Underside has tiny pores (not gills, not smooth — that's the false turkey tail).",
  },
  {
    slug: "shaggy-mane",
    name: "Shaggy Mane",
    scientificName: "Coprinus comatus",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12],
    shoulder: [9, 1],
    habitat: "Disturbed soil — lawns, roadsides, mulch beds — often after rain.",
    notes: "Tall white shaggy cylinder that auto-digests into black ink within 24 hours of picking. Cook same day. One of the few mushrooms you can safely eat without a spore print.",
    caution: "Don't drink alcohol within 48 hours of eating any Coprinus relative.",
  },
  {
    slug: "meadow-mushroom",
    name: "Meadow Mushroom",
    scientificName: "Agaricus campestris",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12, 1, 2, 3],
    shoulder: [4, 9],
    habitat: "Pasture, grass-lawn, fairy rings — well-grazed open land.",
    notes: "Pink-to-chocolate gills, white cap, no chemical scent. Tastes like a cleaner button mushroom. Avoid yellow-staining or phenol-smelling lookalikes.",
    caution: "Agaricus xanthodermus stains bright yellow and causes GI upset — always rub the cap and base before harvest.",
  },
  {
    slug: "prince-mushroom",
    name: "Prince Mushroom",
    scientificName: "Agaricus augustus",
    category: "mushrooms",
    regions: ALL,
    peak: [4, 5, 6, 10, 11, 12],
    shoulder: [3, 9],
    habitat: "Under cedars and conifers in residential yards, redwood parks.",
    notes: "Big tan-scaled cap, white-then-chocolate gills, ringed stem with a strong almond-marzipan scent. One of the best-flavored wild Agaricus.",
    caution: "Same yellow-staining warning as meadow mushroom — confirm almond smell, not phenol.",
  },
  {
    slug: "blewit",
    name: "Blewit",
    scientificName: "Clitocybe nuda",
    wikiTitle: "Lepista_nuda",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2],
    shoulder: [10, 3],
    habitat: "Composted leaf litter, mulch piles, redwood duff.",
    notes: "Violet-lilac cap, gills, and stem when young, fading to tan with age. Pink spore print. Earthy, slightly perfumed flavor. Always cook — raw blewits cause GI upset.",
    caution: "Several purple Cortinarius mushrooms are deadly — confirm pink (not rusty-brown) spore print before eating.",
  },
  {
    slug: "wood-ear",
    name: "Wood Ear",
    scientificName: "Auricularia americana",
    wikiTitle: "Auricularia_auricula-judae",
    category: "mushrooms",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4],
    shoulder: [10, 5],
    habitat: "Dead alder and elderberry, also on bay laurel after wet winters.",
    notes: "Gelatinous ear-shaped brown brackets — exactly the wood ear of hot-and-sour soup. Dries to brittle and rehydrates in minutes.",
  },
  {
    slug: "lobster",
    name: "Lobster Mushroom",
    scientificName: "Hypomyces lactifluorum",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [9, 10, 11, 12],
    habitat: "Fir / Doug-fir — coastal mountains.",
    notes: "A parasitic mold (Hypomyces) growing on a Russula host. Firm, dense, with shellfish-like flavor. The orange crust is the giveaway.",
  },
  {
    slug: "saffron-milk-cap",
    name: "Saffron Milk Cap",
    scientificName: "Lactarius deliciosus",
    category: "mushrooms",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [11, 12, 1, 2],
    shoulder: [10, 3],
    habitat: "Pine plantations — especially Monterey pine.",
    notes: "Bright orange cap with concentric rings; bleeds carrot-orange milk when cut, often staining green-blue with age. Firm, nutty — best grilled or pan-roasted.",
  },
  {
    slug: "velvet-shank",
    name: "Velvet Shank (Wild Enoki)",
    scientificName: "Flammulina velutipes",
    category: "mushrooms",
    regions: ALL,
    peak: [12, 1, 2, 3],
    shoulder: [11, 4],
    habitat: "Dead hardwood — elm, alder, occasionally bay laurel.",
    notes: "Orange caps on dark velvety stems — the wild ancestor of cultivated enoki. Cook to soften. Cold-resistant; one of the few mushrooms that fruits through frost.",
    caution: "Beware of the deadly Galerina marginata on the same logs — Galerina has a stem ring and rusty spore print.",
  },
  {
    slug: "cauliflower",
    name: "Cauliflower Mushroom",
    scientificName: "Sparassis radicata",
    wikiTitle: "Sparassis",
    category: "mushrooms",
    regions: ["marin", "santa-cruz"],
    peak: [10, 11, 12],
    shoulder: [9, 1],
    habitat: "Base of conifers — Doug-fir, pine.",
    notes: "A football-sized cluster of ribbon-like fleshy leaves. Bright cream, no toxic lookalikes. Tear apart and rinse out the duff before cooking.",
  },
  {
    slug: "gem-studded-puffball",
    name: "Gem-studded Puffball",
    scientificName: "Lycoperdon perlatum",
    category: "mushrooms",
    regions: ALL,
    peak: [9, 10, 11, 12],
    shoulder: [8, 1],
    habitat: "Forest paths, duff, coastal woodlands.",
    notes: "Pear-shaped white ball studded with tiny spines. Slice through — interior must be pure marshmallow-white. Mild tofu-textured flavor; takes anything.",
    caution: "Always slice. Button-stage Amanitas (deadly) appear as a white egg before opening — they show a gill outline inside.",
  },
  {
    slug: "shaggy-parasol",
    name: "Shaggy Parasol",
    scientificName: "Chlorophyllum brunneum",
    category: "mushrooms",
    regions: ALL,
    peak: [10, 11, 12, 1],
    shoulder: [9, 2],
    habitat: "Mulch piles, garden beds, compost-amended soil.",
    notes: "Tall white cap with concentric brown scales, ringed stem, white gills. Always cook — raw causes GI upset in many people. Confirm white (not green) spore print.",
    caution: "C. molybdites — the false parasol — has a green spore print and causes severe vomiting. Always print.",
  },
  {
    slug: "shrimp-russula",
    name: "Shrimp Russula",
    scientificName: "Russula xerampelina",
    category: "mushrooms",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [10, 11, 12, 1],
    shoulder: [9, 2],
    habitat: "Mixed conifer / oak — Doug-fir, tanoak.",
    notes: "Wine-red cap fading to yellow-tan, yellow stem, smells distinctly of shrimp shell when fresh. Mild, sweet, sturdy — uncommon among Russulas.",
    caution: "Most red-capped Russulas are GI irritants. The shrimp smell is the diagnostic feature — no smell, no eat.",
  },

  // ════════════════════════════ WILD GREENS (36) ════════════════════════════
  {
    slug: "miners-lettuce",
    name: "Miner's Lettuce",
    scientificName: "Claytonia perfoliata",
    category: "greens",
    regions: ALL,
    peak: [2, 3, 4, 5],
    shoulder: [1, 6],
    habitat: "Shaded creek banks, oak woodland, north-facing slopes.",
    notes: "Round disk-leaves clasping the stem with a small white flower in the center. Mild, succulent, the gold standard of California wild salad greens.",
  },
  {
    slug: "stinging-nettle",
    name: "Stinging Nettle",
    scientificName: "Urtica dioica",
    category: "greens",
    regions: ALL,
    peak: [2, 3, 4],
    shoulder: [1, 5],
    habitat: "Damp creek beds, redwood understory, partial shade.",
    notes: "Harvest top 6 inches with gloves before flowering. Loses sting when cooked, dried, or blanched. Tastes between spinach and seaweed.",
    caution: "Wear gloves — formic acid on hairs causes a 24-hour rash.",
  },
  {
    slug: "wood-sorrel",
    name: "Wood Sorrel",
    scientificName: "Oxalis oregana",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6, 7, 8, 9],
    shoulder: [2, 10],
    habitat: "Redwood understory, shaded forest floor.",
    notes: "Native clover-like trifoliate leaves with pink-to-white flowers. Lemon-bright sour pop. Use as a finish, not a bulk green — oxalic acid.",
    caution: "High oxalic acid — moderate intake only.",
  },
  {
    slug: "dandelion",
    name: "Dandelion",
    scientificName: "Taraxacum officinale",
    category: "greens",
    regions: ALL,
    peak: [2, 3, 4, 5],
    shoulder: [1, 6, 11, 12],
    habitat: "Lawns, roadsides, vineyard floor — universal.",
    notes: "Toothed-leaf rosette, single yellow flower per hollow stem (compound flowers = false dandelion). Pre-flower leaves are mildest; roast roots as coffee.",
  },
  {
    slug: "bay-laurel-leaves",
    name: "Bay Laurel (leaves)",
    scientificName: "Umbellularia californica",
    category: "greens",
    regions: ALL,
    peak: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    habitat: "Coastal mixed forest, creek bottoms.",
    notes: "Far more aromatic than Mediterranean bay — half a leaf per stew. Dry on the counter for a week before storing.",
    caution: "Strong oils. Never use for tea or baby food.",
  },
  {
    slug: "chickweed",
    name: "Chickweed",
    scientificName: "Stellaria media",
    category: "greens",
    regions: ALL,
    peak: [12, 1, 2, 3, 4],
    shoulder: [11, 5],
    habitat: "Garden beds, shaded lawn, irrigated edges.",
    notes: "Sprawling mat with tiny white star flowers and a single line of hair down the stem. Eat raw — corn-silk sweet, lightly grassy.",
  },
  {
    slug: "common-mallow",
    name: "Common Mallow",
    scientificName: "Malva neglecta",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    habitat: "Sidewalk strips, neglected lots, garden edges.",
    notes: "Round scalloped leaves and small lavender flowers. Tender leaves cook to a silky, slightly mucilaginous green — thickens soups. Green seed pods are 'cheeses' — a kid snack.",
  },
  {
    slug: "lambs-quarters",
    name: "Lamb's Quarters",
    scientificName: "Chenopodium album",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6, 7, 8],
    habitat: "Disturbed soil — vegetable beds, vineyard rows, sidewalk strips.",
    notes: "Diamond leaves with a powdery silver underside on new growth. Cook like spinach — a goosefoot relative of quinoa.",
  },
  {
    slug: "purslane",
    name: "Purslane",
    scientificName: "Portulaca oleracea",
    category: "greens",
    regions: ALL,
    peak: [6, 7, 8, 9],
    habitat: "Garden paths, sidewalk cracks, vegetable rows.",
    notes: "Succulent paddle leaves and red stems. Lemony, slightly mucilaginous. Highest plant source of omega-3.",
  },
  {
    slug: "watercress",
    name: "Watercress",
    scientificName: "Nasturtium officinale",
    category: "greens",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4, 5],
    habitat: "Cold, clean, fast-moving creeks and springs.",
    notes: "Pinnately compound leaves floating on running water. Bright peppery bite.",
    caution: "Only harvest from water you'd drink — giardia and ag runoff risk. Cook if uncertain of source.",
  },
  {
    slug: "hairy-bittercress",
    name: "Hairy Bittercress",
    scientificName: "Cardamine hirsuta",
    category: "greens",
    regions: ALL,
    peak: [11, 12, 1, 2, 3, 4],
    shoulder: [10, 5],
    habitat: "Winter rains anywhere with bare soil — nurseries, garden edges.",
    notes: "Tiny rosette of round leaflets with explosive seed pods. Bright peppery, exactly like watercress, with no waterborne pathogen risk.",
  },
  {
    slug: "sheep-sorrel",
    name: "Sheep Sorrel",
    scientificName: "Rumex acetosella",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6],
    shoulder: [2, 7],
    habitat: "Acidic disturbed soil, road cuts, dry pasture.",
    notes: "Arrow-shaped leaves with twin lobes at the base. Sharp lemon zing — exactly what cultivated French sorrel tastes like, in a smaller leaf.",
    caution: "Oxalic acid — moderate intake only.",
  },
  {
    slug: "sow-thistle",
    name: "Sow Thistle",
    scientificName: "Sonchus oleraceus",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6, 7],
    shoulder: [2, 8, 9],
    habitat: "Disturbed soil, garden edges, sidewalk strips.",
    notes: "Soft-spined dandelion relative with bigger, milder leaves. Cook out the bitterness like cultivated chicory.",
  },
  {
    slug: "shepherds-purse",
    name: "Shepherd's Purse",
    scientificName: "Capsella bursa-pastoris",
    category: "greens",
    regions: ALL,
    peak: [1, 2, 3, 4, 11, 12],
    shoulder: [5, 10],
    habitat: "Garden beds, gravel paths, winter rows.",
    notes: "Heart-shaped seed pods are the giveaway. Leaves taste like peppery cabbage; pods are a tiny mustard pop on top of fish or eggs.",
  },
  {
    slug: "plantain",
    name: "Broadleaf Plantain",
    scientificName: "Plantago lanceolata",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    habitat: "Lawns, trail edges, compacted soil.",
    notes: "Parallel-veined leaves in a flat rosette. Young leaves cook tender; older ones are fibrous. Crushed leaves draw bee stings and itches.",
  },
  {
    slug: "pineapple-weed",
    name: "Pineapple Weed",
    scientificName: "Matricaria discoidea",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6, 7, 8],
    habitat: "Compacted gravel — driveways, trail centers, parking lots.",
    notes: "Looks like rayless chamomile; crushed flowers smell like pineapple. Steeped fresh or dried into the gentlest of teas.",
  },
  {
    slug: "wild-onion",
    name: "Wild Onion",
    scientificName: "Allium triquetrum",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6],
    shoulder: [2],
    habitat: "Coastal scrub, oak savanna, shaded road cuts — three-cornered leek is invasive in much of the Bay.",
    notes: "If it smells like onion, it's an onion. Three-cornered leek has the most bulb mass. Bulb, leaf, and flower are all usable.",
    caution: "Death camas grows in the same habitat and is fatal — only harvest plants that smell of onion when crushed.",
  },
  {
    slug: "yerba-buena",
    name: "Yerba Buena",
    scientificName: "Clinopodium douglasii",
    category: "greens",
    regions: ALL,
    peak: [5, 6, 7, 8, 9],
    shoulder: [4, 10],
    habitat: "Redwood / Doug-fir understory, well-drained shade.",
    notes: "The 'good herb' that named San Francisco. Trailing mint vine — soft, sweet, restorative tea.",
  },
  {
    slug: "mugwort",
    name: "Mugwort",
    scientificName: "Artemisia douglasiana",
    category: "greens",
    regions: ALL,
    peak: [3, 4, 5, 6, 7],
    habitat: "Creek bottoms, oak woodland edges.",
    notes: "Silver-backed lobed leaves with a strong sage-bay scent. Bitter — use as a smoking herb, dream pillow, or moxa, not a salad green.",
    caution: "Avoid during pregnancy.",
  },
  {
    slug: "fennel",
    name: "Fennel",
    scientificName: "Foeniculum vulgare",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    shoulder: [11, 2],
    habitat: "Roadside, fallow fields, freeway embankments — invasive everywhere in the Bay.",
    notes: "Fronds year-round, pollen in summer, green seed in late summer, brown seed by fall. Pollen is the prize — gold dust over fish or cured meat.",
  },
  {
    slug: "wild-radish",
    name: "Wild Radish",
    scientificName: "Raphanus raphanistrum",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [2, 3, 4, 5, 6],
    habitat: "Same disturbed fields as wild mustard — often growing alongside it.",
    notes: "Lavender or white four-petal flowers (mustard is yellow). Pods are the prize — crisp, peppery, like rat-tail radish. Pickle while still green.",
  },
  {
    slug: "wild-mustard",
    name: "Wild Mustard",
    scientificName: "Hirschfeldia incana",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [2, 3, 4, 5],
    shoulder: [1, 6, 12],
    habitat: "Disturbed fields, vineyard rows, roadside — the dominant Bay Area mustard.",
    notes: "Bright yellow four-petal flowers; leaves and unopened flower buds are pungent like wasabi. Buds are excellent quick-pickled.",
  },
  {
    slug: "nasturtium",
    name: "Nasturtium",
    scientificName: "Tropaeolum majus",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [2, 3, 4, 5, 6, 7],
    shoulder: [1, 8, 12],
    habitat: "Naturalized in nearly every Bay Area shady yard, hill, and road cut.",
    notes: "Round leaves and orange-red trumpet flowers. Leaf, flower, and green seedpod are all peppery and edible. Seedpods quick-pickle like capers.",
  },
  {
    slug: "wild-oat",
    name: "Wild Oat",
    scientificName: "Avena fatua",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [4, 5, 6],
    shoulder: [3, 7],
    habitat: "Annual grasslands — the hills of the East Bay and Marin are blanketed in it.",
    notes: "Harvest milky-stage seeds for tincture, or thresh and winnow mature seed for porridge. Greens have value as a calcium-rich infusion.",
  },
  {
    slug: "clover",
    name: "Red Clover",
    scientificName: "Trifolium pratense",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6, 7, 8],
    habitat: "Pasture, lawn, ditch edges.",
    notes: "Pinkish-purple ball flowers on trifoliate leaves. Dry flowers for tea — gentle, herbaceous, traditionally a women's tonic.",
  },
  {
    slug: "ice-plant",
    name: "Ice Plant",
    scientificName: "Carpobrotus edulis",
    category: "greens",
    regions: ["marin", "peninsula", "santa-cruz"],
    isInvasive: true,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    habitat: "Coastal bluffs and dunes — the magenta-flowered carpet that's smothering CA's coast.",
    notes: "Aggressively invasive. Fingers of succulent leaves taste like a salt-tart cucumber. Fruit (after spring flowers) is sour and intensely fragrant — a chef's curiosity.",
  },
  {
    slug: "bur-clover",
    name: "Bur Clover",
    scientificName: "Medicago polymorpha",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6],
    shoulder: [2, 7],
    habitat: "Lawns, pasture, vineyard floor.",
    notes: "Three-lobed leaves with a tiny yellow flower. Young leaves are mild, lightly nutty — a salad filler. Burs (mature seedpods) are the namesake stickers.",
  },
  {
    slug: "sea-rocket",
    name: "Sea Rocket",
    scientificName: "Cakile maritima",
    category: "greens",
    regions: ["marin", "peninsula", "santa-cruz"],
    isInvasive: true,
    peak: [4, 5, 6, 7, 8, 9, 10],
    habitat: "Strand line of sandy beaches up and down the CA coast.",
    notes: "Succulent, glaucous leaves with pale lavender four-petal flowers. Sharp, mustardy, faintly horseradish — outstanding raw with oysters.",
  },
  {
    slug: "curly-dock",
    name: "Curly Dock",
    scientificName: "Rumex crispus",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6],
    shoulder: [2, 7],
    habitat: "Field edges, pasture, damp lots.",
    notes: "Long ruffle-edged leaves with a strong sour-lemon punch. Cook to soften. Seeds in fall grind into a buckwheat-style flour.",
    caution: "Oxalic acid — moderate intake only.",
  },
  {
    slug: "cattail",
    name: "Cattail",
    scientificName: "Typha latifolia",
    category: "greens",
    regions: ALL,
    peak: [4, 5, 6],
    shoulder: [3, 7],
    habitat: "Freshwater marsh, pond edges, slow streams.",
    notes: "Spring shoots peel like leeks. Green corn-dog heads are edible boiled before they go to fluff. Pollen in early summer is a golden flour.",
    caution: "Marsh harvest may be restricted in preserves and refuges — check land-use rules.",
  },
  {
    slug: "fiddlehead-fern",
    name: "Fiddlehead Fern",
    scientificName: "Athyrium filix-femina",
    category: "greens",
    regions: ["marin", "santa-cruz"],
    peak: [3, 4, 5],
    shoulder: [2, 6],
    habitat: "Redwood / Doug-fir understory, deep shade near water.",
    notes: "Tight unfurled fronds of lady fern. Pinch the brown papery scales off, then steam or sauté thoroughly — always cook.",
    caution: "Raw fiddleheads cause GI upset; always cook through. Avoid bracken fern (Pteridium aquilinum) — carcinogenic.",
  },
  {
    slug: "wild-asparagus",
    name: "Wild Asparagus",
    scientificName: "Asparagus officinalis",
    category: "greens",
    regions: ["east-bay", "marin"],
    peak: [4, 5],
    shoulder: [3, 6],
    habitat: "Old railroad cuts, ag escapees along ditches.",
    notes: "Look for last year's tall ferny stalks in early spring — that's where this year's spears will push up. Snap, don't cut.",
  },
  {
    slug: "sea-beans",
    name: "Sea Beans",
    scientificName: "Salicornia pacifica",
    wikiTitle: "Salicornia",
    category: "greens",
    regions: ["marin", "east-bay", "peninsula"],
    peak: [5, 6, 7, 8, 9],
    habitat: "Salt marsh edges — San Pablo Bay, Drakes Estero, Tomales.",
    notes: "Jointed succulent stems. Crisp and pre-salted. Pinch the tender tips only.",
    caution: "Marsh harvest is regulated in many CA preserves — check refuge rules.",
  },
  {
    slug: "new-zealand-spinach",
    name: "New Zealand Spinach",
    scientificName: "Tetragonia tetragonoides",
    category: "greens",
    regions: ["marin", "peninsula", "santa-cruz"],
    isInvasive: true,
    peak: [5, 6, 7, 8, 9, 10],
    habitat: "Coastal bluffs, beach edges — naturalized along the whole CA coast.",
    notes: "Diamond-shaped fleshy leaves. Cooks down identically to spinach. Blanch briefly to drop oxalates.",
    caution: "High oxalic acid — always blanch before eating.",
  },
  {
    slug: "milk-thistle",
    name: "Milk Thistle",
    scientificName: "Silybum marianum",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6],
    shoulder: [2, 7],
    habitat: "Heavy infestations in disturbed Bay Area pastureland.",
    notes: "Spiny rosette with white-marbled leaves. De-spine and steam ribs like an artichoke; roast seeds for liver-tonic tea (silymarin).",
  },
  {
    slug: "pellitory",
    name: "Pellitory of the Wall",
    scientificName: "Parietaria judaica",
    category: "greens",
    regions: ALL,
    isInvasive: true,
    peak: [3, 4, 5, 6, 7, 8, 9, 10],
    shoulder: [2, 11],
    habitat: "Cracked SF sidewalks, retaining walls, shaded urban edges — naturalized everywhere.",
    notes: "Soft non-stinging nettle relative. Mild grassy greens, best wilted in oil or in a soup base. Aggressive volunteer in any irrigated city garden.",
    caution: "Pollen is a major allergen. Don't disturb plants in flower if you're sensitive.",
  },

  // ════════════════════════════ BERRIES (15) ════════════════════════════
  {
    slug: "himalayan-blackberry",
    name: "Himalayan Blackberry",
    scientificName: "Rubus armeniacus",
    category: "berries",
    regions: ALL,
    isInvasive: true,
    peak: [7, 8, 9],
    shoulder: [6, 10],
    habitat: "Every creek bank, fence line, and disturbed edge in the Bay.",
    notes: "Invasive, abundant, and excellent. Pick when berries pull off the receptacle with no tug. Highest sugar after a hot week.",
  },
  {
    slug: "california-blackberry",
    name: "California Blackberry",
    scientificName: "Rubus ursinus",
    category: "berries",
    regions: ALL,
    peak: [6, 7, 8],
    habitat: "Native cousin of the Himalayan — smaller berries, thinner canes, found in deeper woods.",
    notes: "Less prolific than Himalayan but more nuanced — concentrated berry flavor and a slight winey edge. The parent of the cultivated boysenberry.",
  },
  {
    slug: "california-huckleberry",
    name: "California Huckleberry",
    scientificName: "Vaccinium ovatum",
    category: "berries",
    regions: ["marin", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Acidic redwood / Doug-fir soil.",
    notes: "Small dark berries on glossy evergreen leaves. Sweet-tart, smaller than cultivated blueberry, with a longer shelf life.",
  },
  {
    slug: "thimbleberry",
    name: "Thimbleberry",
    scientificName: "Rubus parviflorus",
    category: "berries",
    regions: ["marin", "santa-cruz"],
    peak: [6, 7, 8],
    habitat: "Redwood understory, coastal shade.",
    notes: "Maple-shaped fuzzy leaves, no thorns. Soft, fragile red caps that fall apart in the hand — eat trail-side or carry on a flat board.",
  },
  {
    slug: "salmonberry",
    name: "Salmonberry",
    scientificName: "Rubus spectabilis",
    category: "berries",
    regions: ["marin"],
    peak: [5, 6, 7],
    habitat: "Wet coastal forest, North Bay creeks.",
    notes: "Golden to salmon-orange raspberry shape. Earliest cane berry of the year. Better in pie than eaten plain.",
  },
  {
    slug: "blue-elderberry",
    name: "Blue Elderberry",
    scientificName: "Sambucus nigra",
    category: "berries",
    regions: ALL,
    peak: [8, 9],
    shoulder: [7],
    habitat: "Stream banks, oak woodland edges.",
    notes: "Powder-blue clusters on umbrella stems. Must cook — raw berries are unpleasantly cyanogenic. Stems and leaves are always toxic.",
    caution: "Red elderberry (S. racemosa) is generally not eaten — only harvest the blue/black species, cooked.",
  },
  {
    slug: "coast-strawberry",
    name: "Coast Strawberry",
    scientificName: "Fragaria chiloensis",
    category: "berries",
    regions: ["marin", "peninsula", "santa-cruz"],
    peak: [5, 6, 7],
    habitat: "Coastal bluffs and dunes.",
    notes: "One of the two parents of the cultivated strawberry. Tiny, concentrated, with a brighter perfume than supermarket berries.",
  },
  {
    slug: "wild-strawberry",
    name: "Wild Strawberry",
    scientificName: "Fragaria vesca",
    category: "berries",
    regions: ALL,
    peak: [5, 6, 7],
    shoulder: [4, 8],
    habitat: "Forest edges, oak woodland, shaded trail edges — inland counterpart to Coast Strawberry.",
    notes: "Woodland strawberry — even smaller and brighter than the coastal species. Wild-strawberry's pop of flavor is the entire reason people grow them.",
  },
  {
    slug: "california-gooseberry",
    name: "California Gooseberry",
    scientificName: "Ribes californicum",
    category: "berries",
    regions: ALL,
    peak: [5, 6, 7],
    habitat: "Oak understory, riparian shade — common in Marin and East Bay.",
    notes: "Spiny green-to-purple berry. Cook into pies, sorbet, or savory pan sauces. Spines on the fruit drop softness once cooked.",
  },
  {
    slug: "red-flowering-currant",
    name: "Red Flowering Currant",
    scientificName: "Ribes sanguineum",
    category: "berries",
    regions: ALL,
    peak: [6, 7, 8],
    shoulder: [5, 9],
    habitat: "Oak / Doug-fir edges — the showy pink-flowered hedge of late winter.",
    notes: "Dark blue-black berry with a powdery bloom. More valued as a winter pollinator plant than as fruit, but the berries make a tart jelly.",
  },
  {
    slug: "coffeeberry",
    name: "Coffeeberry",
    scientificName: "Frangula californica",
    category: "berries",
    regions: ALL,
    peak: [7, 8, 9],
    shoulder: [6, 10],
    habitat: "Chaparral, oak woodland — all four regions.",
    notes: "Coffee-bean-shaped berries that ripen green → red → black on the same cluster. Historically used by native peoples as a laxative — not a food berry. Best left to the birds.",
    caution: "Mild laxative effect — do not eat in quantity. Bark and unripe berries amplify the effect.",
  },
  {
    slug: "manzanita-berry",
    name: "Manzanita Berry",
    scientificName: "Arctostaphylos manzanita",
    category: "berries",
    regions: ALL,
    peak: [8, 9],
    shoulder: [7, 10],
    habitat: "Chaparral, granite slopes — all four regions.",
    notes: "'Little apples' — dry, mealy, intensely apple-flavored. Best cold-water steeped into a cider or pressed for syrup. Don't try to eat raw.",
  },
  {
    slug: "hawthorn",
    name: "Hawthorn",
    scientificName: "Crataegus monogyna",
    category: "berries",
    regions: ALL,
    isInvasive: true,
    peak: [9, 10, 11],
    habitat: "Naturalized hedgerows, abandoned plantings.",
    notes: "Bright red haws — mealy, mildly sweet, traditionally heart tonic. Strain the seeds (cyanogenic) and use flesh for jelly or 'haw butter'.",
    caution: "Seeds are cyanogenic. Cook and strain.",
  },
  {
    slug: "toyon",
    name: "Toyon (Christmas Berry)",
    scientificName: "Heteromeles arbutifolia",
    category: "berries",
    regions: ALL,
    peak: [11, 12, 1],
    habitat: "Chaparral and oak woodland — all regions.",
    notes: "Bright red clusters at Christmas-time. Native peoples roasted or boiled them — never eat raw (cyanogenic, like blue elderberry). Cook into jelly or a roasted nibble.",
    caution: "Raw berries contain cyanogenic compounds — always cook.",
  },
  {
    slug: "salal",
    name: "Salal",
    scientificName: "Gaultheria shallon",
    category: "berries",
    regions: ["marin", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Coastal Doug-fir / redwood understory.",
    notes: "Dark blue-black berries on leathery oval leaves. Mealy texture, mild blueberry-grape flavor — better cooked into jam than eaten raw.",
  },

  // ════════════════════════════ FRUITS (9) ════════════════════════════
  {
    slug: "california-bay-nut",
    name: "California Bay Nut",
    scientificName: "Umbellularia californica",
    // Same Wikipedia page as bay laurel — different harvest, same plant
    wikiTitle: "Umbellularia",
    category: "fruits",
    regions: ALL,
    peak: [10, 11, 12],
    habitat: "Beneath bay laurel — drop in late fall.",
    notes: "Olive-shaped green-purple fruit; the seed inside is the prize. Roast at 400°F for 15 minutes, peel — tastes like dark chocolate × coffee × bay.",
    caution: "Always roast — raw nuts have psychoactive umbellulone.",
  },
  {
    slug: "wild-plum",
    name: "Wild Plum",
    scientificName: "Prunus subcordata",
    category: "fruits",
    regions: ["east-bay", "santa-cruz"],
    peak: [7, 8, 9],
    habitat: "Foothill oak woodland — native CA plum.",
    notes: "Yellow-orange to red plum, sharper and more aromatic than store plums. Excellent for fruit leather and umeshu-style infusions.",
  },
  {
    slug: "hollyleaf-cherry",
    name: "Hollyleaf Cherry",
    scientificName: "Prunus ilicifolia",
    category: "fruits",
    regions: ["east-bay", "peninsula", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Chaparral, dry oak slopes — leathery holly-like evergreen leaves.",
    notes: "Marble-sized purple-red cherries — thin layer of sweet flesh over a large pit. Make jelly or grind the seed historically (after careful leaching).",
    caution: "Seeds are cyanogenic. Eat the flesh, discard the pit.",
  },
  {
    slug: "rose-hip",
    name: "Rose Hip",
    scientificName: "Rosa californica",
    category: "fruits",
    regions: ALL,
    peak: [9, 10, 11],
    habitat: "Coastal scrub, riparian — California wild rose is everywhere.",
    notes: "Best after the first frost. Split, scrape seeds (irritating fuzz), and use the flesh for syrup, jelly, or vitamin-C tea.",
  },
  {
    slug: "california-wild-grape",
    name: "California Wild Grape",
    scientificName: "Vitis californica",
    category: "fruits",
    regions: ALL,
    peak: [8, 9, 10],
    habitat: "River corridors throughout the Bay.",
    notes: "Small intensely tart blue grapes with big seeds. Leaves for dolmas, fruit for verjus and jelly.",
  },
  {
    slug: "madrone-berry",
    name: "Madrone Berry",
    scientificName: "Arbutus menziesii",
    category: "fruits",
    regions: ALL,
    peak: [9, 10, 11],
    habitat: "Mixed evergreen and oak forest — all regions.",
    notes: "Pebbly red-orange berries from the iconic peeling-bark tree. Mealy and lightly sweet — historically a flour ingredient and a cider base.",
  },
  {
    slug: "lemonade-berry",
    name: "Lemonade Berry",
    scientificName: "Rhus integrifolia",
    category: "fruits",
    regions: ["santa-cruz"],
    peak: [5, 6, 7, 8, 9],
    shoulder: [4, 10],
    habitat: "Coastal chaparral, south-facing bluffs — Santa Cruz and southward.",
    notes: "Sticky pink-red berries with a tart-sweet coating. Cold-water steep for 30 minutes, strain, sweeten lightly — instant pink lemonade.",
  },
  {
    slug: "california-hazelnut",
    name: "California Hazelnut",
    scientificName: "Corylus cornuta",
    category: "fruits",
    regions: ["marin", "santa-cruz"],
    peak: [8, 9, 10],
    habitat: "Cool shaded canyons, redwood / Doug-fir understory.",
    notes: "Small wild filbert with a long bristly husk. Race the squirrels — they go fast. Roast lightly to peel the brown skin.",
  },
  {
    slug: "prickly-pear",
    name: "Prickly Pear",
    scientificName: "Opuntia ficus-indica",
    category: "fruits",
    regions: ALL,
    isInvasive: true,
    peak: [8, 9, 10],
    habitat: "Old homesteads, naturalized on dry slopes.",
    notes: "Magenta fruit. Singe glochids off over a flame or scrub under running water before peeling. Watermelon-bubblegum sweetness. Young pads (nopales) are also edible after de-spining.",
    caution: "Glochids — tiny barbed hairs — embed in skin and persist. Always use tongs and gloves.",
  },
];

/**
 * Item count per category — used by the filter chips.
 */
export function countByCategory(): Record<ForageCategory, number> {
  return FORAGE_ITEMS.reduce(
    (acc, item) => {
      acc[item.category]++;
      return acc;
    },
    { mushrooms: 0, greens: 0, berries: 0, fruits: 0 } as Record<ForageCategory, number>,
  );
}

export function countInvasive(): number {
  return FORAGE_ITEMS.filter((i) => i.isInvasive).length;
}

/**
 * Items in peak in a given month — used by the spotlight and "X species can be
 * found in {month}" stat.
 */
export function itemsInPeak(month: number): ForageItem[] {
  return FORAGE_ITEMS.filter((i) => i.peak.includes(month));
}

/**
 * Items where the given month is either peak or shoulder — used for the
 * Month View species count (matches Bay Forager's tally).
 */
export function itemsAvailable(month: number): ForageItem[] {
  return FORAGE_ITEMS.filter(
    (i) => i.peak.includes(month) || i.shoulder?.includes(month),
  );
}
