import { redirect, notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { EditorialHero } from "@/components/shared/EditorialHero";
import { EditTaskForm } from "@/components/admin/tasks/EditTaskForm";
import type { FarmTask } from "@/types/database";

export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function EditTaskPage({ params }: PageProps) {
  const { id } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const admin = createAdminClient();

  const [{ data: taskRow }, { data: items }] = await Promise.all([
    admin.from("farm_tasks").select("*").eq("id", id).maybeSingle(),
    admin
      .from("items")
      .select("id, name")
      .eq("is_archived", false)
      .order("name", { ascending: true }),
  ]);

  if (!taskRow) notFound();
  const task = taskRow as FarmTask;

  return (
    <div className="min-h-screen">
      <EditorialHero
        eyebrow="Operations"
        title="Edit task"
        subtitle={
          task.source === "manual"
            ? "One-off task"
            : `Generated · ${task.source}` // hint that auto tasks may be regenerated by cron
        }
        flower="borage-2"
        backHref="/admin/tasks"
      />
      <div className="max-w-md mx-auto px-4 py-6">
        {task.source !== "manual" && (
          <div className="mb-4 rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">
            This task was generated automatically. Your edits stick, but the
            nightly cron may supersede them if the underlying schedule
            changes.
          </div>
        )}
        <EditTaskForm task={task} items={items ?? []} />
      </div>
    </div>
  );
}
