"use client";

import { useState } from "react";

interface RecommendationsResponse {
  recommendations: string;
  generated_at: string;
  window: { start: string; end: string };
  totals: { total_revenue: number; total_expenses: number; gross_margin: number };
}

/**
 * AI-generated planting recommendations for the upcoming season.
 *
 * Pulls 12 months of deliveries + expenses + current plantings, sends to
 * Claude Opus 4.7 with adaptive thinking, and renders the model's
 * markdown-format reply (## heading + - bullet only). Generation is
 * on-demand — Opus calls cost $0.05–0.15 each, so we don't auto-run.
 */
export function CropRecommendations() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<RecommendationsResponse | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/crop-recommendations", { method: "POST" });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "Failed to generate");
      setData(json);
    } catch (err: any) {
      setError(err.message ?? "Failed to generate");
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="px-4 py-6 max-w-3xl mx-auto">
      <div className="bg-white rounded-2xl border border-pf-master-violet/15 shadow-sm overflow-hidden">
        <div className="px-5 py-4 bg-pf-master-violet/[0.04] border-b border-pf-master-violet/10 flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <p className="section-eyebrow text-pf-master-violet">AI Recommendations</p>
            <p className="text-xs text-farm-muted mt-1 leading-snug">
              Strategic planting guidance based on the last 12 months of deliveries, expenses, and your current plantings. Generated by Claude Opus 4.7 — takes 30–60 seconds.
            </p>
          </div>
          <button
            type="button"
            onClick={generate}
            disabled={loading}
            className="text-xs font-medium px-3 py-2 rounded-lg bg-pf-master-violet text-white hover:bg-pf-master-violet/90 disabled:opacity-50 disabled:cursor-not-allowed min-h-0 flex-shrink-0 inline-flex items-center gap-1.5 whitespace-nowrap"
          >
            <span aria-hidden="true">✨</span>
            <span>{loading ? "Thinking…" : data ? "Regenerate" : "Generate"}</span>
          </button>
        </div>

        {error && (
          <div className="px-5 py-3 bg-red-50 border-b border-red-100">
            <p className="text-sm text-red-700">{error}</p>
          </div>
        )}

        {loading && !data && (
          <div className="px-5 py-8 text-center">
            <div className="inline-block w-8 h-8 border-2 border-pf-master-violet/30 border-t-pf-master-violet rounded-full animate-spin" />
            <p className="text-xs text-farm-muted mt-3">
              Analyzing 12 months of farm data…
            </p>
          </div>
        )}

        {data && (
          <div className="px-5 py-5">
            <RecommendationsView text={data.recommendations} />
            <div className="mt-5 pt-3 border-t border-farm-dark/5 flex items-center justify-between text-[10px] tracking-wider uppercase text-farm-muted/70">
              <span>
                Window: {data.window.start} → {data.window.end}
              </span>
              <span>
                Revenue ${formatMoney(data.totals.total_revenue)} · Expenses ${formatMoney(data.totals.total_expenses)}
              </span>
            </div>
          </div>
        )}

        {!data && !loading && !error && (
          <div className="px-5 py-6 text-center text-sm text-farm-muted">
            Click <span className="font-semibold text-pf-master-violet">Generate</span> when you&apos;re thinking about next season&apos;s plan.
          </div>
        )}
      </div>
    </section>
  );
}

/**
 * Bare-bones markdown renderer for the constrained output format the
 * route's system prompt enforces (## heading + - bullet lines, no
 * bold/italic/code). Avoids dragging in react-markdown for ~10 lines of
 * formatting.
 */
function RecommendationsView({ text }: { text: string }) {
  const lines = text.trim().split("\n");
  const blocks: Array<{ type: "heading" | "bullet" | "para" | "spacer"; content: string }> = [];

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      blocks.push({ type: "spacer", content: "" });
      continue;
    }
    if (line.startsWith("## ")) {
      blocks.push({ type: "heading", content: line.slice(3).trim() });
    } else if (line.startsWith("- ") || line.startsWith("* ")) {
      blocks.push({ type: "bullet", content: line.slice(2).trim() });
    } else {
      blocks.push({ type: "para", content: line });
    }
  }

  // Group adjacent bullets into a single <ul> so spacing and styling read
  // as a list, not a stack of orphan items.
  const grouped: Array<{ type: "heading" | "para" | "spacer" | "list"; content: string | string[] }> = [];
  for (const b of blocks) {
    if (b.type === "bullet") {
      const last = grouped[grouped.length - 1];
      if (last?.type === "list") {
        (last.content as string[]).push(b.content);
      } else {
        grouped.push({ type: "list", content: [b.content] });
      }
    } else if (b.type === "spacer") {
      const last = grouped[grouped.length - 1];
      if (last?.type !== "spacer") grouped.push({ type: "spacer", content: "" });
    } else {
      grouped.push({ type: b.type, content: b.content });
    }
  }

  return (
    <div className="space-y-3">
      {grouped.map((b, i) => {
        if (b.type === "heading") {
          return (
            <h3
              key={i}
              className="font-display text-base text-farm-dark mt-3 first:mt-0 pt-2 first:pt-0 border-t border-farm-dark/5 first:border-0"
            >
              {b.content as string}
            </h3>
          );
        }
        if (b.type === "list") {
          return (
            <ul key={i} className="space-y-1.5 text-sm text-farm-dark leading-relaxed">
              {(b.content as string[]).map((bullet, j) => (
                <li key={j} className="flex gap-2">
                  <span className="text-pf-master-violet flex-shrink-0 select-none">•</span>
                  <span>{bullet}</span>
                </li>
              ))}
            </ul>
          );
        }
        if (b.type === "para") {
          return (
            <p key={i} className="text-sm text-farm-dark leading-relaxed">
              {b.content as string}
            </p>
          );
        }
        return null;
      })}
    </div>
  );
}

function formatMoney(n: number): string {
  return n.toLocaleString("en-US", { maximumFractionDigits: 0 });
}
