"use client";

import { useState } from "react";
import { SimpleMarkdown } from "@/components/shared/SimpleMarkdown";
import { formatDateTimePacific } from "@/lib/utils";

interface AuditResponse {
  report: string;
  generated_at: string;
  item_count: number;
}

/**
 * Audit client — single big "Generate" CTA, then renders the markdown
 * the route returns. Suggestion-only — no automatic apply. Cost is one
 * Opus 4.7 call per click (~\$0.30-0.50), so we don't auto-run on mount.
 */
export function CatalogAuditClient({ itemCount }: { itemCount: number }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [data, setData] = useState<AuditResponse | null>(null);

  async function generate() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/ai/catalog-audit", { method: "POST" });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "Failed to generate");
      setData(json);
    } catch (err: any) {
      setError(err.message ?? "Failed to generate");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="px-4 py-6 max-w-3xl mx-auto">
      <div className="bg-white rounded-2xl border border-pf-master-violet/15 shadow-sm overflow-hidden">
        <div className="px-5 py-4 bg-pf-master-violet/[0.04] border-b border-pf-master-violet/10 flex items-start justify-between gap-3">
          <div className="flex-1 min-w-0">
            <p className="section-eyebrow text-pf-master-violet">Catalog Hygiene</p>
            <p className="text-xs text-farm-muted mt-1 leading-snug">
              Reviews all {itemCount} active items and suggests duplicates to merge and parent/child groupings — calibrated to Johnny&apos;s Selected Seeds standards. Pure suggestion: nothing is changed automatically. Generated by Claude Opus 4.7, takes 60-90 seconds.
            </p>
          </div>
          <button
            type="button"
            onClick={generate}
            disabled={loading || itemCount === 0}
            className="text-xs font-medium px-3 py-2 rounded-lg bg-pf-master-violet text-white hover:bg-pf-master-violet/90 disabled:opacity-50 disabled:cursor-not-allowed min-h-0 flex-shrink-0 inline-flex items-center gap-1.5 whitespace-nowrap"
          >
            <span aria-hidden="true">✨</span>
            <span>{loading ? "Auditing…" : data ? "Regenerate" : "Generate"}</span>
          </button>
        </div>

        {error && (
          <div className="px-5 py-3 bg-red-50 border-b border-red-100">
            <p className="text-sm text-red-700">{error}</p>
          </div>
        )}

        {loading && !data && (
          <div className="px-5 py-10 text-center">
            <div className="inline-block w-8 h-8 border-2 border-pf-master-violet/30 border-t-pf-master-violet rounded-full animate-spin" />
            <p className="text-xs text-farm-muted mt-3">
              Reading the full catalog…
            </p>
            <p className="text-[11px] text-farm-muted/70 mt-1">
              Opus 4.7 with adaptive thinking — this can take a minute or two.
            </p>
          </div>
        )}

        {data && (
          <div className="px-5 py-5">
            <SimpleMarkdown text={data.report} />
            <div className="mt-5 pt-3 border-t border-farm-dark/5 flex items-center justify-between text-[10px] tracking-wider uppercase text-farm-muted/70">
              <span>Reviewed {data.item_count} items</span>
              <span>{formatDateTimePacific(data.generated_at)}</span>
            </div>
            <div className="mt-4 px-3 py-2.5 rounded-lg bg-amber-50 border border-amber-200">
              <p className="text-[11px] text-amber-900 leading-snug">
                <span className="font-semibold">Reminder:</span> these are suggestions only. Merging items is destructive (price history, order line items lost) — apply duplicates manually after reviewing each one. Parent/child groupings are reversible — set them by editing each child item and picking a Parent.
              </p>
            </div>
          </div>
        )}

        {!data && !loading && !error && (
          <div className="px-5 py-8 text-center text-sm text-farm-muted">
            Click <span className="font-semibold text-pf-master-violet">Generate</span> to scan the catalog.
          </div>
        )}
      </div>
    </div>
  );
}
