-- ============================================
-- Press Farm OS — Migration 042: Event Request Groups
-- ============================================
-- Chefs submit multiple item lines under one event in a single
-- submission (rather than one event_request per request). This adds an
-- explicit group identifier so the admin queue can present the full
-- event together and offer a single Accept-all / Decline-all action.
--
-- Existing single-item rows from migration 041 stay valid (group_id is
-- nullable); the chef and admin UIs treat a NULL group as a group of one.

ALTER TABLE event_requests
  ADD COLUMN IF NOT EXISTS event_group_id uuid;

CREATE INDEX IF NOT EXISTS idx_event_requests_group
  ON event_requests(event_group_id);

COMMENT ON COLUMN event_requests.event_group_id IS
  'UUID linking all event_request rows submitted together under one event order. NULL means the request was filed standalone (legacy migration 041 rows, or a single-item submission). Generated by the API at submission time.';
